server:
  port: 8080

jwt:
  secret: 'VzKOIWzxkoinU1RzrgGty2oMAfOWcLPOg4VOAXau0zdT1hMFjB'
  expiration_time: 4320000000


spring:
  datasource:
    url: jdbc:h2:mem:board-db
    username: root
    password: rootpwd

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
